const tape = require("tape");
const bent = require("bent");
const getPort = require("get-port");
const nock = require("nock");

const server = require("../");

const getJSON = bent("json");
const getBuffer = bent("buffer");

nock("https://nodejs.org")
  .persist(true)
  .get("/dist/index.json")
  .reply(200, [
    {
      version: "v14.9.0",
      date: "2020-08-26",
      files: [
        "aix-ppc64",
        "headers",
        "linux-arm64",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-s390x",
        "linux-x64",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "6.14.8",
      v8: "8.4.371.19",
      uv: "1.39.0",
      zlib: "1.2.11",
      openssl: "1.1.1g",
      modules: "83",
      lts: false,
      security: false,
    },
    {
      version: "v14.8.0",
      date: "2020-08-11",
      files: [
        "aix-ppc64",
        "headers",
        "linux-arm64",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-s390x",
        "linux-x64",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "6.14.7",
      v8: "8.4.371.19",
      uv: "1.38.1",
      zlib: "1.2.11",
      openssl: "1.1.1g",
      modules: "83",
      lts: false,
      security: false,
    },
    {
      version: "v13.4.0",
      date: "2019-12-17",
      files: [
        "aix-ppc64",
        "headers",
        "linux-arm64",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-s390x",
        "linux-x64",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "sunos-x64",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "6.13.4",
      v8: "7.9.317.25",
      uv: "1.34.0",
      zlib: "1.2.11",
      openssl: "1.1.1d",
      modules: "79",
      lts: false,
      security: true,
    },
    {
      version: "v13.3.0",
      date: "2019-12-03",
      files: [
        "aix-ppc64",
        "headers",
        "linux-arm64",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-s390x",
        "linux-x64",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "sunos-x64",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "6.13.1",
      v8: "7.9.317.25",
      uv: "1.33.1",
      zlib: "1.2.11",
      openssl: "1.1.1d",
      modules: "79",
      lts: false,
      security: false,
    },
    {
      version: "v4.9.1",
      date: "2018-03-29",
      files: [
        "headers",
        "linux-arm64",
        "linux-armv6l",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "sunos-x64",
        "sunos-x86",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "2.15.11",
      v8: "4.5.103.53",
      uv: "1.9.1",
      zlib: "1.2.11",
      openssl: "1.0.2o",
      modules: "46",
      lts: "Argon",
      security: false,
    },
    {
      version: "v4.9.0",
      date: "2018-03-28",
      files: [
        "headers",
        "linux-arm64",
        "linux-armv6l",
        "linux-armv7l",
        "linux-ppc64le",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "src",
        "sunos-x64",
        "sunos-x86",
        "win-x64-7z",
        "win-x64-exe",
        "win-x64-msi",
        "win-x64-zip",
        "win-x86-7z",
        "win-x86-exe",
        "win-x86-msi",
        "win-x86-zip",
      ],
      npm: "2.15.11",
      v8: "4.5.103.53",
      uv: "1.9.1",
      zlib: "1.2.11",
      openssl: "1.0.2o",
      modules: "46",
      lts: "Argon",
      security: true,
    },
    {
      version: "v0.12.18",
      date: "2017-02-22",
      files: [
        "headers",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "osx-x86-tar",
        "src",
        "sunos-x86",
        "win-x64-exe",
        "win-x86-exe",
        "win-x86-msi",
      ],
      npm: "2.15.11",
      v8: "3.28.71.20",
      uv: "1.6.1",
      zlib: "1.2.8",
      openssl: "1.0.1u",
      modules: "14",
      lts: false,
      security: false,
    },
    {
      version: "v0.12.17",
      date: "2016-10-18",
      files: [
        "headers",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "osx-x86-tar",
        "src",
        "sunos-x64",
        "sunos-x86",
        "win-x64-exe",
        "win-x86-exe",
        "win-x86-msi",
      ],
      npm: "2.15.1",
      v8: "3.28.71.19",
      uv: "1.6.1",
      zlib: "1.2.8",
      openssl: "1.0.1u",
      modules: "14",
      lts: false,
      security: true,
    },
    {
      version: "v0.12.16",
      date: "2016-09-27",
      files: [
        "headers",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "osx-x86-tar",
        "src",
        "sunos-x64",
        "sunos-x86",
        "win-x64-exe",
        "win-x86-exe",
        "win-x86-msi",
      ],
      npm: "2.15.1",
      v8: "3.28.71.19",
      uv: "1.6.1",
      zlib: "1.2.8",
      openssl: "1.0.1u",
      modules: "14",
      lts: false,
      security: true,
    },
    {
      version: "v0.12.15",
      date: "2016-06-23",
      files: [
        "headers",
        "linux-x64",
        "linux-x86",
        "osx-x64-pkg",
        "osx-x64-tar",
        "osx-x86-tar",
        "src",
        "sunos-x64",
        "sunos-x86",
        "win-x64-exe",
        "win-x86-exe",
        "win-x86-msi",
      ],
      npm: "2.15.1",
      v8: "3.28.71.19",
      uv: "1.6.1",
      zlib: "1.2.8",
      openssl: "1.0.1t",
      modules: "14",
      lts: false,
      security: true,
    },
  ]);

const context = {};

tape("setup", async function (t) {
  const port = await getPort();
  context.server = server.listen(port);
  context.origin = `http://localhost:${port}`;

  t.end();
});

tape("should get dependencies", async function (t) {
  const html = (await getBuffer(`${context.origin}/dependencies`)).toString();
  t.equals(html.indexOf("bent") > -1, true, "should contain bent");
  t.equals(html.indexOf("express") > -1, true, "should contain express");
  t.equals(html.indexOf("handlebars") > -1, true, "should contain handlebars");
});

tape("should get minimum secure versions", async function (t) {
  const result = await getJSON(`${context.origin}/minimum-secure`);
  t.equals(result["v0"].version, "v0.12.17", "version should match");
  t.equals(result["v4"].version, "v4.9.0", "version should match");
});

tape("should get latest-releases", async function (t) {
  const result = await getJSON(`${context.origin}/latest-releases`);
  t.equals(result["v14"].version, "v14.9.0", "version should match");
  t.equals(result["v13"].version, "v13.4.0", "version should match");
});

tape("teardown", function (t) {
  context.server.close();
  t.end();
});
